language: python
python:
    - "2.7"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy python-nose
install: python setup.py build_ext --inplace
script: make test
